# Generated by Django 5.1.5 on 2025-02-10 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("stocks", "0002_stock_about_stock_exclusive_stock_legal_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="aadhar_card_image",
            new_name="demat_acc_image",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="aadhar_card_validated",
            new_name="demat_acc_validated",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="is_valid",
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("verification_pending", "Verification Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="verification_pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="demat_account",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="total_investment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_screenshot",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=4, max_digits=16),
                ),
                ("date_of_purchase", models.DateField(blank=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks.stock"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
