# Generated by Django 5.1.5 on 2025-01-29 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser'),
        ('stocks', '0002_rename_averagetradedprice_stockdata_average_traded_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='stock_name',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stock',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='stocks.stockdata'),
            preserve_default=False,
        ),
    ]
