# Generated by Django 5.1.5 on 2025-01-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('ISIN', models.CharField(max_length=12, unique=True)),
                (
                    'FaceValue',
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    'TotalShare',
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    'TotalIncome',
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    'ProfileAfterTax',
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ('EPS', models.DecimalField(decimal_places=2, max_digits=20)),
                ('PE', models.DecimalField(decimal_places=2, max_digits=20)),
                ('PB', models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    'MarketCapitalization',
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    'EnterpriseValue',
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    'BookValue',
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    'IntrinsicValue',
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    'EarningYields',
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ('Sector', models.CharField(max_length=255)),
                ('SubSector', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                (
                    'CashflowOperation',
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    'CashflowFinancing',
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    'AverageTradedPrice',
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
            ],
        ),
    ]
