# Generated by Django 5.1.5 on 2025-01-30 13:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isin", models.CharField(max_length=12, unique=True)),
                ("stock_name", models.CharField(max_length=255)),
                ("stock_symbol", models.CharField(max_length=10)),
                (
                    "company_logo",
                    models.URLField(
                        default="https://cdn.logo.com/hotlink-ok/logo-social.png"
                    ),
                ),
                ("face_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_share", models.DecimalField(decimal_places=2, max_digits=20)),
                ("total_income", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "profile_after_tax",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("eps", models.DecimalField(decimal_places=2, max_digits=20)),
                ("pe", models.DecimalField(decimal_places=2, max_digits=20)),
                ("pb", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "market_capitalization",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "enterprise_value",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("book_value", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "intrinsic_value",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "earning_yields",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("sector", models.CharField(max_length=255)),
                ("sub_sector", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                (
                    "cashflow_operation",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "cashflow_financing",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "average_traded_price",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=16)),
                ("date", models.DateField(default=datetime.date.today)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_values",
                        to="stocks.stock",
                    ),
                ),
            ],
        ),
    ]
