# Generated by Django 5.1.5 on 2025-01-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='AverageTradedPrice',
            new_name='average_traded_price',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='BookValue',
            new_name='book_value',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='CashflowFinancing',
            new_name='cashflow_financing',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='CashflowOperation',
            new_name='cashflow_operation',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='EPS',
            new_name='earning_yields',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='EarningYields',
            new_name='enterprise_value',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='EnterpriseValue',
            new_name='eps',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='FaceValue',
            new_name='face_value',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='IntrinsicValue',
            new_name='intrinsic_value',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='ISIN',
            new_name='isin',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='MarketCapitalization',
            new_name='market_capitalization',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='PB',
            new_name='pb',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='PE',
            new_name='pe',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='ProfileAfterTax',
            new_name='profile_after_tax',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='Sector',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='SubSector',
            new_name='stock_name',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='TotalIncome',
            new_name='total_income',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='TotalShare',
            new_name='total_share',
        ),
        migrations.AddField(
            model_name='stockdata',
            name='stock_symbol',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='sub_sector',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
