# Generated by Django 5.1.5 on 2025-02-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="exclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="legal_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="lot_size",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="top_pick",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="trending",
            field=models.BooleanField(default=False),
        ),
    ]
